### ISSUE TITLE
Callback was already called

### ISSUE THREAD

**Issue by endquote** [wavded/winston-mail#18] opened 2015-02-24 20:23 UTC
I'm getting the following callstack when trying to send mail via winston 0.9.0 and winston-mail 0.3.1.

```
C:\Stimulant\Source\UBE-360\ampm\node_modules\winston\node_modules\async\lib\async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at C:\Stimulant\Source\UBE-360\ampm\node_modules\winston\node_modules\async\lib\async.js:30:31
    at C:\Stimulant\Source\UBE-360\ampm\node_modules\winston\lib\winston\logger.js:187:9
    at Object.callback (C:\Stimulant\Source\UBE-360\ampm\node_modules\winston-mail\lib\winston-mail.js:90:5)
    at connect (C:\Stimulant\Source\UBE-360\ampm\node_modules\winston-mail\node_modules\emailjs\smtp\client.js:69:19)
    at caller (C:\Stimulant\Source\UBE-360\ampm\node_modules\winston-mail\node_modules\emailjs\smtp\smtp.js:49:14)
    at Socket.response (C:\Stimulant\Source\UBE-360\ampm\node_modules\winston-mail\node_modules\emailjs\smtp\smtp.js:135:9)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:129:20)
    at net.js:923:16
    at process._tickCallback (node.js:355:11)
```

My config is basically like this:

```
{
	host: "my.smtp", 
	ssl: false, 
	username: "myuser@domain", 
	from: "myuser@domain",
	password: "mypass",
	level: "error", 
	to: "myuser@domain" 
}
```

I've had it working successfully in the past, but have recently updated all modules in my project, so I guess something broke. Since the callstack doesn't include any of my code, I'm unsure how to troubleshoot.

**Comment by wavded** [comment] 2015-02-24 22:44
hmm.... wonder if something changed in winston 0.9.0

**Comment by endquote** [comment] 2015-03-02 21:40
I did some more tests. Seems like something broke in winston-mail 0.3.1.

winston 0.9.0 and winston-mail 0.3.1: fail
winston 0.8.3 and winston-mail 0.3.1: fail
winston 0.7.3 and winston-mail 0.3.1: fail
winston 0.7.3 and winston-mail 0.2.7: success
winston 0.7.3 and winston-mail 0.3.0: success
winston 0.9.0 and winston-mail 0.3.0: success

**Comment by wavded** [comment] 2015-03-05 18:49
odd, do you have a minimal reproducible example I could try?

**Comment by endquote** [comment] 2015-03-06 00:01
This repros for me.

```
var winston = require('winston');
var logger = new winston.Logger();
logger.add(require('winston-mail').Mail, { to: "com@net.org" });
logger.error('foo');
```

**Comment by wavded** [comment] 2015-03-06 04:09
Thanks, I was able to duplicate.  Looks like this is an issue in `emailjs`.

https://github.com/eleith/emailjs/pull/116

I confirmed the PR fixes the issue.  Hopefully that can get merged in soon and I will update the package.

**Comment by wavded** [comment] 2015-03-06 16:55
@endquote just published a version with the fixed version of `emailjs`, let me know if you have any more issues.

**Closed by wavded** 2015-03-06 16:55 UTC

**Comment by endquote** [comment] 2015-03-06 17:36
Looks good! Thanks for looking into it.

**Comment by DmitryPogodaev** [comment] 2015-04-06 04:29
Hello!

Just updated with npm update && npm rebuild. 
Current version of winston-mail:
  "version": "0.3.2",
And emailjs:
  "version": "0.3.13"

First i get this error:
>2015-04-06T03:53:31.506Z - error: Realtime.chooseCardAsGuesser currentRound.updatePhase error: Error: Current phaseId equal newPhaseId: 3 | gameId=93, cardId=128, userId=43
>2015-04-06T03:53:32.109Z - error: Realtime.chooseCardAsGuesser currentRound.updatePhase error: Error: Current phaseId equal newPhaseId: 3 | gameId=93, cardId=469, userId=8

And just after that I have this error:
>stack=[Error: Callback was already called.,
>at D:\OpenServer\domains\imagine-server\www\node_modules\async\lib\async.js:30:31,
>at D:\OpenServer\domains\imagine-server\www\node_modules\winston\lib\winston\logger.js:187:9,
>at Object.callback (D:\OpenServer\domains\imagine-server\www\node_modules\winston-mail\lib\winston-mail.js:90:5), 
>at connect (D:\OpenServer\domains\imagine-server\www\node_modules\winston-mail\node_modules\emailjs\smtp\client.js:69:19),
>at caller (D:\OpenServer\domains\imagine-server\www\node_modules\winston-mail\node_modules\emailjs\smtp\smtp.js:49:14),
>at Socket.response (D:\OpenServer\domains\imagine-server\www\node_modules\winston-mail\node_modules\emailjs\smtp\smtp.js:138:9),
>at Socket.g (events.js:199:16),
>at Socket.emit (events.js:129:20),
>at net.js:451:14,
>at process._tickCallback (node.js:355:11)]

This chain of code cause the error:

```javascript
async.eachSeries(mustMove, function(userId, callback) {
  ...
  hub.realtime.chooseCardAsGuesser(game, cardId, game.players.id(userId));            
  ...
}, function(err){ 
  ...
  return;
});

chooseCardAsGuesser: function (game, cardId, user) {
  ...
  return game.currentRound.updatePhase (game.id, 3, function (err, result) {
    if (err) return hub.logger.log('error', 'Realtime.chooseCardAsGuesser currentRound.updatePhase error: '+err, {gameId: game.id, cardId: cardId, userId: user._id}); 
    ...
  }
  ...
}

roundSchema.methods.updatePhase = function (gameId, newPhaseId, callback) {
  ...
  if (round.phaseId == newPhaseId) return callback (new Error('Current phaseId equal newPhaseId: '+newPhaseId));
  ...
}
```
What information i can provide to help you investigate this?

**Comment by endquote** [comment] 2015-06-15 22:34
I'm still seeing this:

```
var log = require('winston');
var mail = require('winston-mail').Mail;
log.add(log.transports.Mail, { to: 'josh@endquote.com' });
log.error('foo');
log.error('bar'); // if I remove this line, it doesn't die
```
